services:

  # chunking:
  #   image: us-central1-docker.pkg.dev/desarrollo-cloud-457900/desarrollo-cloud/chunking:latest
  #   container_name: chunking
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     CLOUD_STORAGE: bucket-documents-users
  #   networks:
  #     - project_network
  #   restart: always
  
  embeddings_doc:
    container_name: embeddings_doc
    image: us-central1-docker.pkg.dev/desarrollo-cloud-457900/desarrollo-cloud/embeddings_doc:latest
    ports:
      - "8002:8002"
    networks:
      - project_network
    restart: always

  embeddings_prompt:
    container_name: embeddings_prompt
    image: us-central1-docker.pkg.dev/desarrollo-cloud-457900/desarrollo-cloud/embeddings_prompt:latest
    ports:
      - "8003:8003"
    networks:
      - project_network
    restart: always

  retriever:
    container_name: retriever
    image:  us-central1-docker.pkg.dev/desarrollo-cloud-457900/desarrollo-cloud/retriever:latest
    ports:
      - "8004:8004"
    networks:
      - project_network
    restart: always

  augment:
    container_name: augment
    image: us-central1-docker.pkg.dev/desarrollo-cloud-457900/desarrollo-cloud/augment:latest
    ports:
      - "8005:8005"
    environment:
      API_KEY: AIzaSyArjlDoowr7cU_8bPpISEZkoUB257xs2Ec
    networks:
      - project_network
    restart: always
 
networks:
  project_network:
    driver: bridge

volumes:
  #chunking:
    #driver: local
  embeddings_docs:
    driver: local
  embeddings_prompt:
    driver: local
  retriever:
    driver: local
  augment:
    driver: local