services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - project_network

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: backend
    image: backend:latest
    expose:
      - "8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://team5:Project2025!@relational_db:5432/USER
    networks:
      - project_network
    restart: always
    depends_on:
      - relational_db

  relational_db:
    build:
      context: ./relational_db
      dockerfile: Dockerfile
    container_name: relational_db
    image: relational_db:latest
    environment:
      POSTGRES_DB: USER
      POSTGRES_USER: team5
      POSTGRES_PASSWORD: Project2025!
      POSTGRES_PORT: 5432
    volumes:
      - relational_db:/var/lib/postgresql/data
    networks:
      - project_network
    expose:
      - "5432"
    restart: always

networks:
  project_network:
    driver: bridge

volumes:
  relational_db:
    driver: local
