services:


  # -----------------------------------------------------------------------------
  # Lógica Retriever (PostgreSQL Vectorial)
  # -----------------------------------------------------------------------------
  augment:
    
    image: us-central1-docker.pkg.dev/desarrollo-web-451923/cloud-images/aumentador:latest
    container_name: augment
    ports:
      - "2000:2000"
    depends_on:
      - retriever
    networks:
      - project_network
    volumes:
      - augment:/var/lib/augment/data
    restart: always

  # -----------------------------------------------------------------------------
  # Lógica Retriever (PostgreSQL Vectorial)
  # -----------------------------------------------------------------------------
  retriever:
    image: us-central1-docker.pkg.dev/desarrollo-web-451923/cloud-images/retriever
    container_name: retriever
    ports:
      - "8080:8080"
    #depends_on:
      #- vectorial_db
    networks:
      - project_network
    volumes:
      - retriever:/var/lib/retriever/data
    restart: always

# -----------------------------------------------------------------------------
# Chunking
# -----------------------------------------------------------------------------
  chunking:
    image: us-central1-docker.pkg.dev/desarrollo-web-451923/cloud-images/chunking:latest
    container_name: chunking_service
    ports:
      - "8001:8001"
    networks:
      - project_network

# -----------------------------------------------------------------------------
# Embeddings
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# 1
# -----------------------------------------------------------------------------
  embeddings1: 
    container_name: embeddings_service_1
    image: us-central1-docker.pkg.dev/desarrollo-web-451923/cloud-images/embeddings:latest
    ports:
      - "8002:8002"
    #depends_on:
      #- vectorial_db
    networks:
      - project_network

# -----------------------------------------------------------------------------
# 2
# # -----------------------------------------------------------------------------
  # embeddings2:
  #   build:
  #     context: ./embeddings
  #     dockerfile: embedings.dockerfile  
  #   container_name: embeddings_service_2
  #   image: embeddings2:latest
  #   depends_on:
  #     - vectorial_db
  #   ports:
  #     - "8003:8002"
  #   networks:
  #     - project_network


# -----------------------------------------------------------------------------
# NETWORKS & VOLUMES
# -----------------------------------------------------------------------------

networks:
  project_network:
    driver: bridge

volumes:
  vectorial_db:
    driver: local
  relational_db:
    driver: local
  ollama:
    driver: local
  frontend:
    driver: local
  retriever:
    driver: local
  augment:
    driver: local
    